### ISSUE TITLE
Adpative in searching for the limit

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#102]
# Status

Done. Added `try_k_more_times`: 9bbe94146cd55e751687d8f95ccd0b52a5124e98

# Note

Set the options (e.g., `ftol_rel` and `ftol_abs`) that usually lead to faster search. If the search fails, will retry by changing the options (e.g., lowering `ftol_rel` and/or `ftol_abs`, using another set of starting values.

# To-Do
- [ ] Select options to change.
- [ ] Revise `ci_bound_wn_i()` to accept user supplied starting values.
- [ ] Revise `ci_i_one()` to check the results and retry if necessary. The history of the attempts should be adapted.
