### ISSUE TITLE
Clean up the test files

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#103]
# Note

There are a lot of test files, with obsolete code commented out.

# To-Do

- [x] Plan sets of test files to be run (e.g., some needs to be run interactively using `testthat::test_file()`, some needs to be run only occasionally because they are slow, some can be run locally in parallel but should not be run on CRAN.
- [x] Clean up the test files.
- [x] Use known results if possible.
- [x] Add `skip*` functions.
