### ISSUE TITLE
Update to the next major version

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#109]
# To-Dos

- [x] Check the documentation of new functions.
- [x] Check the documentation of old functions.
- [x] Check the documentation of functions: Are all classes documented?
- [x] Proofread the examples.
- [x] Proofread the vignettes.
- [x] Update NEWS.
- [x] Update DESCRIPTION.
- [x] Test by `testthat`.
- [x] Check by `pkgdown::build_site()`
- [x] Check by `devtools::check()`.
