### ISSUE TITLE
Make it CRAN ready

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#110]
# To-Dos

- [ ] DESCRIPTION: title: Less than 65 characters
- [ ] DESCRIPTION: title: Title Case.
- [ ] DESCRIPTION: title: Nouns preferred. For verbs, use first-person forms.
- [ ] DESCRIPTION: description: Do not start with "This package ..." or package name.
- [ ] DESCRIPTION: description: Can omit subjects for verbs.
- [ ] DESCRIPTION: description: For verbs, use 3rd-person forms.
- [ ] Function documentation: @details: For verbs, include subjects.
- [ ] Function documentation: @details: For verbs, use 3rd-person forms.
- [ ] Function documentation: Does it have @return?
- [ ] Check @return: If it is called for its side effect, state so.
- [ ] Check @return: If it returns an object of a class, describe the class.
- [ ] Check all vignettes and examples: If they change the environment (e.g., use options()), do they undo the changes on exit?
- [ ] Proofread the examples.
- [ ] Proofread the vignettes.
- [ ] Update NEWS.
- [ ] Check each package in "Suggests": Is it really need to be suggested?
- [ ] Check each package in "Suggests": Do functions that use it check if it is installed, e.g., by requireNamespace()?
- [ ] Check version in DESCRIPTION.
- [ ] Check version in NEWS.md.
- [ ] Test by `devtools::test()`.
- [ ] Check by `pkgdown::build_site()`
- [ ] Check by `devtools::check`.

**Comment by sfcheung** [comment]
Replaced by a project-level issue.
