### ISSUE TITLE
Add more test for semlbci. ci_bound_wn_i may work while semlbci does for some models.

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#111]
# To-Dos
- [x] Add a test for the CFA example in lavaan.
- [x] Add a test for the SEM example in lavaan.
- [x] Add a test for the mutligroup example in lavaan.
- [x] Add a test for the mediation example in lavaan.
- [x] Check if `semlbci()` can be used on the CFA example.
- [x] Check if `semlbci()` can be used on the SEM example.
- [x] Check if `semlbci()` can be used on the multigroup example.
- [x] Check if `semlbci()` can be used on the mediation example.
