### ISSUE TITLE
Check and update all examples and documentation

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#61]
# Status
- Tests passed.

# To-Dos
- [x] semlbci
- [x] semlbci-package
- [x] syntax_to_i
- [x] set_start_wn
- [x] test_constr
- [x] get_names_from_ptable
- [x] get_std_genfct
- [x] get_std_i
- [x] get_std
- [x] print_cibound
- [x] print_semlbci
- [x] scaling_factor
- [x] set_constraint
- [x] get_lhs_op_rhs
- [x] gen_unique_name
- [x] find_variance_in_free
- [x] find_dependent
- [x] find_free
- [x] ci_bound_wn_i
- [x] check_sem_out
- [x] ci_i
- [x] data
- [x] enforce_eq_by_label
