### ISSUE TITLE
Update the vignette

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#85]
# To-Do
- [x] Add robust LBCI.
- [x] Update the content.
- [x] Rename from quick_start to semlbci.
