### ISSUE TITLE
Profile the functions to see why some functions are slow

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#90]
# To-Do
- [ ] Profile `ci_bound_wn_i()` for standardized solution.
- [ ] Profile `ci_bound_wn_i()` for robust standardized solution.
- [ ] Profile `ci_bound_wn_i()` for robust unstandardized solution.
- [ ] Profile `ci_bound_wn_i()` for standardized solution in multiple-group models.
- [ ] Profile `ci_bound_wn_i()` for robust standardized solution in multiple-group models.
- [ ] Profile `ci_bound_wn_i()` for robust unstandardized solution in multiple-group models.

# Possible Issues
- Reduce the use of `lavaan::parameterTable()`.
- Implement some operations by Rcpp.

# Note
Note urgent. Do this after everything works.
