### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#91]
# Note
Some revisions are done ad hoc, to solve an urgent problem. Need to go through the files and clean up the code.
Do this after everything works as expected.

# To-Dos
- [x] semlbci
- [x] loglike_at
- [x] semlbci-package
- [x] check_sem_out
- [x] ci_bound_wn_i
- [x] ci_i_one
- [x] confint_semlbci
- [x] data_mg
- [x] data
- [x] data2
- [x] data3
- [x] find_free
- [x] find_variance_in_free
- [x] free_in_std
- [x] gen_unique_name
- [x] get_i_from_lor
- [x] get_lhs_op_rhs
- [x] get_names_from_ptable
- [x] get_std_genfct
- [x] i_to_name
- [x] lav_mod_to_ram
- [x] print_cibound
- [x] print_semlbci
- [x] ram_to_lav_mod
- [x] remove_intercepts
- [x] remove_v1
- [x] remove_variances
- [x] scaling_factor3
- [x] set_bounds
- [x] set_constraint
- [x] set_start_wn
- [x] std_lav
- [x] std_ram
- [x] syntax_to_i
- [x] test_constr
