### ISSUE TITLE
Rearrange the columns in the output of `semlbci()` and its print method

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#93]
# To-Do
- [x] Print: Hide group if there is only one group. (3c3be37a7f3da4743f436cee8767177419ccd07b)
- [x] Print: Hide label if no parameters have labels. (3c3be37a7f3da4743f436cee8767177419ccd07b)
- [x] Add a label column. (9592328321a08600bfb242f4622850d2e5fc394c)
- [x] The order of first few columns should be id, lhs, op, rhs, gp. (7cfbff547c44f230cbf56ab30bd275c91a39ff93)
