### ISSUE TITLE
Write functions to get the standardized solution of a parameter

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#94]
# To-Do
- [x] Write a function to get the estimate from a set of lavaan model matrices using the row position in the parameter table. Can use `lavaan::lav_model_get_parameters` with `type = "user"` and `extra = TRUE"`. (3a8309f1f59f6438b38c4a9af5430bf76897c75f)
- [x] Write a function to convert one set of lavaan model matrices to a set of RAM matrices. (9a0becde089961493ceb0ab2692fdb1db90db2f0)
- [x] Write a function to get the standardized solution for a set of RAM matrcies. (9a0becde089961493ceb0ab2692fdb1db90db2f0)
- [x] Write a function to convert the set of RAM matrices to a set of lavaan model matrices. (d162dcbee51abebbac176395574cbb5429df5361)
