### ISSUE TITLE
Revise functions that use `lavaan::standardizedSolution()` to use `std_lav()` if instructed

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlbci#95]
# To-Do
- [X] scaling_factor2 (733fba1951155031a340de9621dbb8c2fe3b300c)
- [X] ci_bound_wn_i (4600d9502ffcdb06f251b02be8a69273623b03af)
- [X] get_std (b2317270579d311cde718b9672180ee6828b9e9b)
